<div id="page-wrapper">
			<div class="main-page">
<?php
echo('<p><h3 class="title1">ABOUT US</h3></p>');

?>
<div class="blank-page widget-shadow scroll" id="style-2 div1">
					<p><h3> About SERC</h3>
SERC, housed at the Strathmore University, offers training, research and consultancy services as well as undertaking projects in the energy sector with particular focus on Renewable Energy Technologies (RETs). SERC intends to carve out a niche as an applied technology centre where Renewable Energy Technologies (RETs) are researched on, tested and adapted for local conditions. <br>
SERC has undertaken several projects such installing a 600kW rooftop grid connected solar PV system which will reduce Strathmore University's operational cost and make it the first university in SSA to have a "zero carbon footprint" this will also be the biggest solar PV rooftop in Africa. It has commissioned a 10kW car port hybrid solar/diesel grid connected system to be constructed in the university. This system will not only provide additional energy but also be incorporated for use in the training of solar technicians.<br>
SERC houses the Renewable Energy and Energy Efficiency Competence Centre of East Africa (partnership between the GIZ and Strathmore University) whose main objective is to provide a platform for training, policy discussions, quality certification and awareness creation in the field of renewable energy and energy conservation in East Africa. The partnership will support the Kenyan government in the implementation of the new regulations in licensing and certification of solar technicians and in implementation of the energy management regulations in Kenya. In addition, SERC is collaborating with National Commission for Science and Technology and Innovation (NACOSTI) to carry out research on the replacement of kerosene lighting system in the rural areas of Kenya with pico-PV products.<br>
SERC has recognized that demand is greatest for qualified technicians and the business community in the renewable energy field currently suffers of a dire need of qualified people who can design, install and maintain RETs. This is the market that SERC will seek to satisfy and is already engaged in training of technicians in various RETs.<br>
Moreover, SERC offers consultancy services at all stages in the design and implementation of both renewable and conventional energy projects. Due to the high deficiency of energy expertise in East Africa, it provides professional and technical consultancy services by consolidating a pool of local and international experts from various fields who will apply their unique skills in providing solutions in the region.
Lastly, SERC is invested in affordable energy monitoring systems for energy generation, energy distribution and consumption. Through an in house initiative of one of its pilot projects, SERC started a development of its own monitoring system through open shared software and local developers.
</p><p><br><br><h3>About GIZ Pro-Solar</h3>
As a federally owned enterprise, the Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ)  GmbH  supports  the  German  Government  in  achieving  its  objectives  in  the  field  of international cooperation for sustainable development. <br>
The project “Promotion of Solar-Hybrid Mini-Grids” (ProSolar) is implemented by GIZ on behalf of the German Federal Ministry for Economic Cooperation and Development (BMZ). The project is part of the German Climate Technology Initiative (DKTI) and promotes the dissemination of technologies in emerging and developing countries with the aim of reducing greenhouse gas emissions. Implementing agencies for the DKTI are both GIZ for technical and KfW for financial assistance. The project’s objective is to improve the electrification of remote areas in Kenya through minigrids with  the  participation  of  the  private  sector.  It  furthermore  contributes  to  the improvement  of  the  regulatory  framework  governing  electricity  supply  in  Kenya. Institutional support is provided to public as well as private sector actors to strengthen their capacities in implementation and operation of sustainable and environmentally friendly solar hybrid village power systems.<br>
As a support to the Rural Electrification Authority (REA) of Kenya, as well as mini-grid project developers, GIZ ProSolar takes up the assignment of creating a publically available monitoring system for mini-grids in Kenya, which can be used by mini-grid developers to track and monitor system operation, but also by REA to cumulate data and get a better understanding of mini-grid production and connection rates and thus of rural electrification.</p>
				</div>
</div>
</div>